name: 音乐生成
description: 音乐生成
title: "音乐生成"
labels: ["music_generation"]
body:
  - type: textarea
    id: input_text
    attributes:
      label: "歌词"
      description: 请输入要谱曲的歌词（只能是中文，无标点）：
      placeholder: 
      value: 
    validations:
      required: true
