name: check update
on:
  workflow_dispatch:
    inputs:
      force-version:
        description: "version tag(eg. 1.2.3)"
        default: ""
        required: true
      force-update-type:
        description: "1 for update config"
        required: true
        default: "0"
  schedule:
  - cron: '0 0 */3 * *'
jobs:
  check-update:
    name: check update
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        check-type: ['standard','dev']
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Setup requirements
        run: pip install -r scripts/requirements.txt
        
      - name: ${{matrix.check-type}} version check and build
        id: check_with_python
        run: python scripts/mainUpdate.py ${{matrix.check-type}} ${{github.event.inputs.force-version}}

      - name: ${{matrix.check-type}} upload and generate
        if: steps.check_with_python.outputs.update_url != ''
        id: update_with_node
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./scripts/update.js')
            await script({
              github,
              context,
              core,
              checkType:"${{matrix.check-type}}",
              update_version:"${{steps.check_with_python.outputs.update_version}}",
              forceVersion:"${{github.event.inputs.force-version}}",
              forceUpdate:"${{github.event.inputs.force-update-type}}"
            })

      - name: git push
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.check_with_python.outputs.update_url != ''
        with:
          commit_message: ${{steps.update_with_node.outputs.commit_message}}
          
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
