name: Build Vue
on:
  push:
    branches:    
      - front-end-vite
concurrency: 
  group: build
  cancel-in-progress: true
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Auto release
      run: |
        npm install
        npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./dist/
    - uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: store
        folder: ./dist/
