name: music
on:
  issues:
    types: [opened,edited]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        pip install paddlepaddle
        pip install music21
        pip install protobuf==3.20.0
        python music.py $BODY
        dir
      env:
          BODY: ${{ github.event.issue.body }}
    - uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: store
        folder: result
    - uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{ github.event.issue.body }}
        split-by: "歌词 \n "
    - uses: mad9000/actions-find-and-replace-string@2
      id: findandreplace
      with:
        source: ${{ steps.split.outputs._1}} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
        find: "\n"        # we want to remove ref/heads/ from source 
        replace: ''               # and replace it with a blank string (ie. removing it)
    - name: Create comment
      uses: actions-cool/issues-helper@v2
      with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 ${{ github.event.issue.user.login }} ，生成结果如下：
            midi格式下载地址为（导入到曲谱软件中无歌词，可在电脑上直接播放）：https://xqy2006.github.io/music_generation/${{ steps.findandreplace.outputs.value }}.midi
            xml格式下载地址为（导入到曲谱软件中有歌词，不可在电脑上直接播放）：https://xqy2006.github.io/music_generation/${{ steps.findandreplace.outputs.value }}.xml
    - name: Close issue
      uses: actions-cool/issues-helper@v2
      with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
